name: Publish release

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create release
      id: create_release
      uses: actions/create-release@latest
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false


  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      run: cargo test --verbose

    - name: Run build
      run: cargo build --release && strip --strip-all ./target/release/tccst && mv ./target/release/tccst ./target/release/tccst-linux

    - name: Upload release
      id: upload-release-linux
      uses: alexellis/upload-assets@0.2.3
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_paths: '["./target/release/tccst-linux"]'


  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      run: cargo test --verbose

    - name: Run build
      run: cargo build --release && mv ./target/release/tccst ./target/release/tccst-macos

    - name: Upload release
      id: upload-release-linux
      uses: alexellis/upload-assets@0.2.3
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_paths: '["./target/release/tccst-macos"]'


  build-windows:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      run: cargo test --verbose

    - name: Run build
      run: cargo build --release

    - name: Upload release
      id: upload-release-windows
      uses: alexellis/upload-assets@0.2.3
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_paths: '["./target/release/tccst.exe"]'
